/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication5;

/**
 *
 * @author Wahyu
 */
public class Kalkulatr extends javax.swing.JFrame {
String angka;
double jumlah ,bil1,bil2;
int pilih;
   
    public Kalkulatr() {
        initComponents();
        angka ="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        butt8 = new javax.swing.JButton();
        butt4 = new javax.swing.JButton();
        butt1 = new javax.swing.JButton();
        butt7 = new javax.swing.JButton();
        butt5 = new javax.swing.JButton();
        butt2 = new javax.swing.JButton();
        buttdot = new javax.swing.JButton();
        butt9 = new javax.swing.JButton();
        butt3 = new javax.swing.JButton();
        buttClear = new javax.swing.JButton();
        butt6 = new javax.swing.JButton();
        butt0 = new javax.swing.JButton();
        buttPlus = new javax.swing.JButton();
        ButtKali = new javax.swing.JButton();
        ButtSamadengan = new javax.swing.JButton();
        buttmin = new javax.swing.JButton();
        Butbagi = new javax.swing.JButton();
        Butsisabagi = new javax.swing.JButton();
        MainPanel = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Exxit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        butt8.setText("8");
        butt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt8ActionPerformed(evt);
            }
        });

        butt4.setText("4");
        butt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt4ActionPerformed(evt);
            }
        });

        butt1.setText("1");
        butt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt1ActionPerformed(evt);
            }
        });

        butt7.setText("7");
        butt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt7ActionPerformed(evt);
            }
        });

        butt5.setText("5");
        butt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt5ActionPerformed(evt);
            }
        });

        butt2.setText("2");
        butt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt2ActionPerformed(evt);
            }
        });

        buttdot.setText(".");
        buttdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttdotActionPerformed(evt);
            }
        });

        butt9.setText("9");
        butt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt9ActionPerformed(evt);
            }
        });

        butt3.setText("3");
        butt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt3ActionPerformed(evt);
            }
        });

        buttClear.setText("C");
        buttClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttClearActionPerformed(evt);
            }
        });

        butt6.setText("6");
        butt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt6ActionPerformed(evt);
            }
        });

        butt0.setText("0");
        butt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt0ActionPerformed(evt);
            }
        });

        buttPlus.setText("+");
        buttPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttPlusActionPerformed(evt);
            }
        });

        ButtKali.setText("*");
        ButtKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtKaliActionPerformed(evt);
            }
        });

        ButtSamadengan.setText("=");
        ButtSamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtSamadenganActionPerformed(evt);
            }
        });

        buttmin.setText("-");
        buttmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttminActionPerformed(evt);
            }
        });

        Butbagi.setText("/");
        Butbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButbagiActionPerformed(evt);
            }
        });

        Butsisabagi.setText("%");
        Butsisabagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButsisabagiActionPerformed(evt);
            }
        });

        MainPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainPanelActionPerformed(evt);
            }
        });

        Back.setText("B");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Exxit.setText("E");
        Exxit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExxitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butt8)
                    .addComponent(butt4)
                    .addComponent(butt1)
                    .addComponent(buttdot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butt5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butt6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butt7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butt9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butt3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butt0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttClear)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttmin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtKali, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Butbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtSamadengan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Butsisabagi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Exxit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt8)
                    .addComponent(butt7)
                    .addComponent(butt9)
                    .addComponent(buttPlus)
                    .addComponent(buttmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt4)
                    .addComponent(butt5)
                    .addComponent(butt6)
                    .addComponent(ButtKali)
                    .addComponent(Butbagi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt1)
                    .addComponent(butt2)
                    .addComponent(butt3)
                    .addComponent(Butsisabagi)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttdot)
                    .addComponent(butt0)
                    .addComponent(buttClear)
                    .addComponent(ButtSamadengan)
                    .addComponent(Exxit))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Kalkulator Sederhana");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt8ActionPerformed
angka += "8";       
MainPanel.setText(angka); 
    }//GEN-LAST:event_butt8ActionPerformed

    private void butt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt9ActionPerformed
angka += "9";       
MainPanel.setText(angka);    
    }//GEN-LAST:event_butt9ActionPerformed

    private void butt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt4ActionPerformed
angka += "4";       
MainPanel.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_butt4ActionPerformed

    private void butt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt5ActionPerformed
angka += "5";       
MainPanel.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_butt5ActionPerformed

    private void butt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt6ActionPerformed
angka += "6";       
MainPanel.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_butt6ActionPerformed

    private void butt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt1ActionPerformed
angka += "1";       
MainPanel.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_butt1ActionPerformed

    private void buttdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttdotActionPerformed
angka += ".";       
MainPanel.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_buttdotActionPerformed

    private void buttminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttminActionPerformed
bil1 = Double.parseDouble(angka);
MainPanel.setText("-");
angka = "";
pilih = 2;        // TODO add your handling code here:
    }//GEN-LAST:event_buttminActionPerformed

    private void ButtKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtKaliActionPerformed
bil1 = Double.parseDouble(angka);
MainPanel.setText("*");
angka = "";
pilih = 3;        // TODO add your handling code here:
    }//GEN-LAST:event_ButtKaliActionPerformed

    private void ButsisabagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButsisabagiActionPerformed
bil1 = Double.parseDouble(angka);
MainPanel.setText("%");
angka = "";
pilih = 5;        // TODO add your handling code here:
    }//GEN-LAST:event_ButsisabagiActionPerformed

    private void butt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt0ActionPerformed
angka += "0";       
MainPanel.setText(angka);
    }//GEN-LAST:event_butt0ActionPerformed

    private void butt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt2ActionPerformed
angka += "2";       
MainPanel.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_butt2ActionPerformed

    private void butt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt3ActionPerformed
angka += "3";       
MainPanel.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_butt3ActionPerformed

    private void butt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt7ActionPerformed
angka += "7";       
MainPanel.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_butt7ActionPerformed

    private void buttClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttClearActionPerformed
MainPanel.setText(angka);
bil1 = 0.0;
bil2 = 0.0;
jumlah = 0.0;
angka = "";
    }//GEN-LAST:event_buttClearActionPerformed

    private void MainPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainPanelActionPerformed

    private void ButtSamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtSamadenganActionPerformed
switch (pilih){
    case 1:
    bil2 = Double.parseDouble(angka);
    jumlah = bil1 + bil2;
    angka = Double.toString(jumlah);
    MainPanel.setText(angka);
    break;
     case 2:
    bil2 = Double.parseDouble(angka);
    jumlah = bil1 - bil2;
    angka = Double.toString(jumlah);
    MainPanel.setText(angka);
    break;
     case 3:
    bil2 = Double.parseDouble(angka);
    jumlah = bil1 * bil2;
    angka = Double.toString(jumlah);
    MainPanel.setText(angka);
    break;
     case 4:
    bil2 = Double.parseDouble(angka);
    jumlah = bil1 / bil2;
    angka = Double.toString(jumlah);
    MainPanel.setText(angka);
    break;
     case 5:
    bil2 = Double.parseDouble(angka);
    jumlah = bil1 % bil2;
    angka = Double.toString(jumlah);
    MainPanel.setText(angka);
    break;
     default :
   
    break;
    
    
}
    // TODO add your handling code here:
    }//GEN-LAST:event_ButtSamadenganActionPerformed

    private void buttPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttPlusActionPerformed
bil1 = Double.parseDouble(angka);
MainPanel.setText("+");
angka = "";
pilih = 1;          // TODO add your handling code here:
    }//GEN-LAST:event_buttPlusActionPerformed

    private void ButbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButbagiActionPerformed
     bil1 = Double.parseDouble(angka);
MainPanel.setText("/");
angka = "";
pilih = 4;     // TODO add your handling code here:
    }//GEN-LAST:event_ButbagiActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
int length =MainPanel.getText().length();
int number =MainPanel.getText().length()-1;

String store;
if(length > 0){
    StringBuilder back = new StringBuilder(MainPanel.getText());
    back.deleteCharAt(number);
    store = back.toString();
    MainPanel.setText(store);
}
    }//GEN-LAST:event_BackActionPerformed

    private void ExxitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExxitActionPerformed
System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_ExxitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulatr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulatr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulatr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulatr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulatr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Butbagi;
    private javax.swing.JButton Butsisabagi;
    private javax.swing.JButton ButtKali;
    private javax.swing.JButton ButtSamadengan;
    private javax.swing.JButton Exxit;
    private javax.swing.JTextField MainPanel;
    private javax.swing.JButton butt0;
    private javax.swing.JButton butt1;
    private javax.swing.JButton butt2;
    private javax.swing.JButton butt3;
    private javax.swing.JButton butt4;
    private javax.swing.JButton butt5;
    private javax.swing.JButton butt6;
    private javax.swing.JButton butt7;
    private javax.swing.JButton butt8;
    private javax.swing.JButton butt9;
    private javax.swing.JButton buttClear;
    private javax.swing.JButton buttPlus;
    private javax.swing.JButton buttdot;
    private javax.swing.JButton buttmin;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
